### ISSUE TITLE
Error reading the video

### ISSUE THREAD

**Issue by JenniferVandoni** [sudheerachary/Mesh-Flow-Video-Stabilization#7]
Hello, when I run:
   python Stabilization.py ../data/shaky-5.avi
or
   python Stabilization.py ../data/small-shaky-5.avi
I get the following error:

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /home/travis/miniconda/conda-bld/conda_1486587069159/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7456
Traceback (most recent call last):
  File "Stabilization.py", line 252, in <module>
    x_motion_meshes, y_motion_meshes, x_paths, y_paths = read_video(cap)
  File "Stabilization.py", line 21, in timed
    result = method(*args, **kwargs)
  File "Stabilization.py", line 52, in read_video
    old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)
cv2.error: /home/travis/miniconda/conda-bld/conda_1486587069159/work/opencv-3.1.0/modules/imgproc/src/color.cpp:7456: error: (-215) scn == 3 || scn == 4 in function ipp_cvtColor

How can I solve this? Should I use another version of opencv? Thank you!

**Comment by HITxyer** [comment]
+1

**Comment by sohee-zoe** [comment]
same issue

**Comment by LS11111** [comment]
same issue

**Comment by yuebaoW** [comment]
+1

**Comment by Aaaangel** [comment]
same issue.... how to solve this problem?
